### PR TITLE
Reduce size and layers

### PR DESCRIPTION
**Pull request by mottosso**
In https://github.com/mottosso/Qt.py/pull/221#issuecomment-318884767 you mentioned it's ginormous size. Here are a few (untested) things we could do about that, there are possibly more.

### CODE REVIEW

**Comment by fredrikaverpil** [comment]
Did you test run this?
I don't think that`devtoolset-4-gcc*-5.3.1` is found unless you already install `centos-release-scl` first.

**Comment by fredrikaverpil** [comment]
Hm, I just now realised the Dockerfile could just be called `Dockerfile-2018` and then we can add v3, v4 etc to each release instead. Or we'd have to rename the Dockerfile allt the time... if you like you can just rename the file in this PR too.

**Comment by mottosso** [comment]
> Did you test run this?

No, these are just examples of what could be done.

**Comment by fredrikaverpil** [comment]
Ok!
I'm cleaning the Dockerfile up a bit here on my end too, building Python from source etc too here. Adding comments to more clearly show what's being installed and why.

**Comment by fredrikaverpil** [comment]
Dockerfile updated and now takes 632 MB.

**Comment by mottosso** [comment]
Bam! That's quite the leap from 4 gb :D

**Comment by mottosso** [comment]
How come you're [building Python](https://github.com/fredrikaverpil/vfxplatform-docker/blob/06301896ce13d3a6a51ade3eb0bfc1d38b150a80/Dockerfile-2018#L65)? :O

**Comment by fredrikaverpil** [comment]
Well, because the Python which comes with CentOS 7 isn't built with gcc 5.3.1. I'm actually not sure how important this is... perhaps it's completely unnecessary. But since gcc was defined, I assumed that Python and all modules should use the same gcc.

**Pull request closed without merging**
